set_powerstream_watts:
  name: Stel PowerStream vermogen in
  description: Zet het doelvermogen van een EcoFlow PowerStream.
  fields:
    serial:
      name: Serienummer
      required: true
      selector:
        text:
    watts:
      name: Vermogen
      required: true
      selector:
        number:
          min: 0
          max: 1600
          step: 10
          unit_of_measurement: W

apply_strategy:
  name: Pas strategie toe
  description: Past de ingestelde lokale strategie direct eenmalig toe.

set_smart_plug:
  name: Zet Smart Plug
  description: Zet een EcoFlow Smart Plug aan of uit.
  fields:
    serial:
      name: Serienummer
      required: true
      selector:
        text:
    "on":
      name: Aan
      required: true
      selector:
        boolean:
